### ISSUE TITLE
Nuevo producto

### ISSUE THREAD

**Issue by Nidev-lab** [zeta-dev-web/stock-front#1]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Quise agregar un nuevo producto.

## Resultado esperado

• Encontrar textos mas informativos a la hora de agregar un nuevo producto.

## Resultado actual

• Varios campos se encuentran sin textos que indiquen que función cumplen.

## Captura

![image](https://github.com/zeta-dev-web/stock-front/assets/53904695/0db19d52-009a-4c46-a1da-53cd365ecb67)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by zeta-dev-web** [comment]
- Se corrige el color la fuente del formulario.

![image](https://github.com/zeta-dev-web/stock-front/assets/64854228/7a17ee4a-e944-46a6-bfa5-6ca2faedf86d)


commit de referencia en rama main:  a71cc88
