### ISSUE TITLE
Nuevo usuario.

### ISSUE THREAD

**Issue by Nidev-lab** [zeta-dev-web/stock-front#2]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Quise agregar un nuevo usuario.

## Resultado esperado

• Que no se muestre ningún tipo de información por consola.

## Resultado actual

• Al registrar un nuevo usuario se muestra información del usuario creado por consola.

## Captura

![image](https://github.com/zeta-dev-web/stock-front/assets/53904695/f178f751-0c13-4979-805c-8a737fc76053)
![image](https://github.com/zeta-dev-web/stock-front/assets/53904695/61913243-1e4b-4975-8ef7-b0890f926b83)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by zeta-dev-web** [comment]
- Se elimina mensaje de consola al crear usuario

Commit de referencia en rama main: [6f2ccb5]
