### ISSUE TITLE
Superposición

### ISSUE THREAD

**Issue by Nidev-lab** [zeta-dev-web/stock-front#3]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• No encontrar una superposición. 

## Resultado actual

• Se encuentra una superpocision del nav con la page 404.

## Captura

![image](https://github.com/zeta-dev-web/stock-front/assets/53904695/fdbd5ba7-f692-43ca-895f-84083cacab49)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by zeta-dev-web** [comment]
- Se corrige la superposición del Navbar con la pagina de error 404.

![image](https://github.com/zeta-dev-web/stock-front/assets/64854228/860731a5-9ea5-4680-86d0-d9fd0e4c09c1)

Commit de referencia en rama main: [9ed1d4a]
